// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKps6UXR3FBj9-wgrcIZl8Z3oa7nUAypU',
    appId: '1:1080188668566:web:842e50bf97cee8238550b7',
    messagingSenderId: '1080188668566',
    projectId: 'nrpwhatsapp-502ce',
    authDomain: 'nrpwhatsapp-502ce.firebaseapp.com',
    storageBucket: 'nrpwhatsapp-502ce.appspot.com',
    measurementId: 'G-TV7367Y9QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeNMbb8A73L6jMcV0MW54PAPwFXP7hSjE',
    appId: '1:1080188668566:android:7c537356734950748550b7',
    messagingSenderId: '1080188668566',
    projectId: 'nrpwhatsapp-502ce',
    storageBucket: 'nrpwhatsapp-502ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJnVJ97EEMJWVRq7IXnyPnH064jphUWAA',
    appId: '1:1080188668566:ios:ced8eafcbf4ef97a8550b7',
    messagingSenderId: '1080188668566',
    projectId: 'nrpwhatsapp-502ce',
    storageBucket: 'nrpwhatsapp-502ce.appspot.com',
    iosClientId: '1080188668566-jaik5v6ased7u5h46qp9kas6g8364sl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappMessenger',
  );
}
